package midtrans

import (
	"crypto/sha256"
	"fmt"
	"math/big"
	"time"
)

const RangeMax = 100000 // 10^5

// generateNumericHash generates a 5-digit numeric hash from the current timestamp
// The hash is generated by hashing the current timestamp in nanoseconds using SHA-256
// and taking the last 5 digits of the resulting hash.
// The generated hash is always 5 digits long, padding with leading zeros if necessary.
//
// Example:
//
//	hash := generateNumericHash()
//	fmt.Println(hash) // Output: 12345
//
// Note:
//
//   - The generated hash is deterministic, meaning that the same timestamp will always produce the same hash.
//   - The hash is not unique, as there are many possible 5-digit numbers.
//   - The hash is not secure, as it can be easily reversed.
//   - The hash is not intended to be used for cryptographic purposes.
//   - The hash is intended to be used for generating unique identifiers.
func generateNumericHash() string {
	timestamp := time.Now().UnixNano()

	hasher := sha256.New()
	fprintf, err := fmt.Fprintf(hasher, "%d", timestamp)
	if err != nil {
		return ""
	}
	if fprintf <= 0 {
		return ""
	}

	hash := hasher.Sum(nil)

	hashInt := new(big.Int).SetBytes(hash)
	num := hashInt.Mod(hashInt, big.NewInt(RangeMax)).Int64()

	return fmt.Sprintf("%05d", num)
}
